### PR TITLE
Email verification controller function created to enable Email verification once logged into the dashboard

### PR DESCRIPTION
**Pull request by syam187**

### CODE REVIEW

**Comment by syam187** [comment]
Email verification, when logging into the dashboard

**Comment by nwaweru** [comment]
Laravel already provides an Email verification function https://laravel.com/docs/9.x/verification

Why are you implementing your own?

**Comment by syam187** [comment]
Hello, good morning.
All i did was create an env file, added my local database. i
successfully migrated it.
in the env file i also include Emailing details, so that once i create an
account to the dashboard i can successfully verify it.

**Comment by nwaweru** [comment]
The home controller already has the `verified` middleware.

`Route::get('/home', [HomeController::class, 'index'])->name('home')->middleware(['auth', 'verified']);`

**Comment by syam187** [comment]
yes, i have seen, i have reviewed my code

**Comment by syam187** [comment]
i have updated UserTableSeeder  with my details
i migrated and seed the databases and successfully served the project.
i push my updates to git

**Comment by nwaweru** [comment]
Ok.

For consistency, set the personal credentials in the env.

Don't forget to update the example env too.

Also, cleanup your code. There are a lot of blank spaces. Check out https://laravel.com/docs/9.x/pint

**Comment by syam187** [comment]
Sure, I will do that.

**Comment by syam187** [comment]
okay.

**Comment by syam187** [comment]
Hello, I wanted to enquire about the interview.

**Comment by nwaweru** [comment]
Hi,

That phase was completed.

Did you receive an email?

**Comment by syam187** [comment]
No, I did not.

**Comment by nwaweru** [comment]
Ok.

The program already started. Maybe next time.

**Comment by syam187** [comment]
Thanks, I will.

**Pull request closed without merging**
